---
- name: installing java in azurepipeline
  hosts: all
  become: yes
  vars:
    java_package: openjdk-17-jdk
  tasks:
  - name: java installing
    ansible.builtin.apt:
      name: "{{java_package}}"
      update_cache: yes
      state: present